# Philippine Tourism

In [28]:
import pandas as pd

In [29]:
df = pd.read_excel('Regional_tourism_data_raw.xlsx')

In [30]:
df

,Region,Province,City/Municipality,Foreign Travelers,Overseas Filipinos,Domestic Travelers,Total
0,NCR,Metro Manila,City of Caloocan,-,-,-,-
1,NCR,Metro Manila,City of Las Piñas,680,-,11202,11882
2,NCR,Metro Manila,City of Makati,208206,8878,347335,564419
3,NCR,Metro Manila,City of Malabon,-,-,-,-
4,NCR,Metro Manila,City of Mandaluyong,39369,-,92706,132075
...,...,...,...,...,...,...,...
772,Region XIII,Surigao del Norte,Others,9225,-,174303,183528
773,Region XIII,Surigao del Sur,Bislig City,7,-,17867,17874
774,Region XIII,Surigao del Sur,Tandag City,56,-,56600,56656
775,Region XIII,Surigao del Sur,Others,-,-,70916,70916
776,Region XIII,Agusan del Norte,Butuan City,1785,-,104119,105904

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 777 entries, 0 to 776
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Region              777 non-null    object
 1   Province            777 non-null    object
 2   City/Municipality   752 non-null    object
 3   Foreign Travelers   777 non-null    object
 4   Overseas Filipinos  777 non-null    object
 5   Domestic Travelers  777 non-null    object
 6   Total               776 non-null    object
dtypes: object(7)
memory usage: 42.6+ KB

In [32]:
df['Foreign Travelers'] = df['Foreign Travelers'].replace('-', '0')
df['Overseas Filipinos'] = df['Overseas Filipinos'].replace('-', '0')
df['Domestic Travelers'] = df['Domestic Travelers'].replace('-', '0')
df['Total'] = df['Total'].replace('-', '0')

In [33]:
df

,Region,Province,City/Municipality,Foreign Travelers,Overseas Filipinos,Domestic Travelers,Total
0,NCR,Metro Manila,City of Caloocan,0,0,0,0
1,NCR,Metro Manila,City of Las Piñas,680,0,11202,11882
2,NCR,Metro Manila,City of Makati,208206,8878,347335,564419
3,NCR,Metro Manila,City of Malabon,0,0,0,0
4,NCR,Metro Manila,City of Mandaluyong,39369,0,92706,132075
...,...,...,...,...,...,...,...
772,Region XIII,Surigao del Norte,Others,9225,0,174303,183528
773,Region XIII,Surigao del Sur,Bislig City,7,0,17867,17874
774,Region XIII,Surigao del Sur,Tandag City,56,0,56600,56656
775,Region XIII,Surigao del Sur,Others,0,0,70916,70916
776,Region XIII,Agusan del Norte,Butuan City,1785,0,104119,105904

In [34]:
#convert to numeric
df['Foreign Travelers'] = pd.to_numeric(df['Foreign Travelers'])
df['Overseas Filipinos'] = pd.to_numeric(df['Overseas Filipinos'])
df['Domestic Travelers'] = pd.to_numeric(df['Domestic Travelers'])
df['Total'] = pd.to_numeric(df['Total'])

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 777 entries, 0 to 776
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Region              777 non-null    object
 1   Province            777 non-null    object
 2   City/Municipality   752 non-null    object
 3   Foreign Travelers   777 non-null    int64
 4   Overseas Filipinos  777 non-null    int64
 5   Domestic Travelers  777 non-null    int64
 6   Total               776 non-null    float64
dtypes: float64(1), int64(3), object(3)
memory usage: 42.6+ KB

In [36]:
df

,Region,Province,City/Municipality,Foreign Travelers,Overseas Filipinos,Domestic Travelers,Total
0,NCR,Metro Manila,City of Caloocan,0,0,0,0.0
1,NCR,Metro Manila,City of Las Piñas,680,0,11202,11882.0
2,NCR,Metro Manila,City of Makati,208206,8878,347335,564419.0
3,NCR,Metro Manila,City of Malabon,0,0,0,0.0
4,NCR,Metro Manila,City of Mandaluyong,39369,0,92706,132075.0
...,...,...,...,...,...,...,...
772,Region XIII,Surigao del Norte,Others,9225,0,174303,183528.0
773,Region XIII,Surigao del Sur,Bislig City,7,0,17867,17874.0
774,Region XIII,Surigao del Sur,Tandag City,56,0,56600,56656.0
775,Region XIII,Surigao del Sur,Others,0,0,70916,70916.0
776,Region XIII,Agusan del Norte,Butuan City,1785,0,104119,105904.0

In [37]:
#checking the provinces
df_provinces = pd.read_excel('Philippine Geography.xlsx', sheet_name='PROVINCE')

In [38]:
df_provinces

   3166-2 Code     Subdivision Name Parent Subdivision
0       PH-ABR                 Abra              PH-15
1       PH-AGN     Agusan del Norte              PH-13
2       PH-AGS       Agusan del Sur              PH-13
3       PH-AKL                Aklan              PH-06
4       PH-ALB                Albay              PH-05
..         ...                  ...                ...
80      PH-ZAN  Zamboanga del Norte              PH-09
81      PH-ZAS    Zamboanga del Sur              PH-09
82       PH-00         Metro Manila                NaN
83         NaN        Cotabato City                NaN
84         NaN         Isabela City                NaN

[85 rows x 3 columns]

In [39]:
len(df)

777

In [40]:
df['Province'].isin(df_provinces['Subdivision Name']).sum()

742

There are provinces that are not on the list

In [41]:
#view provinces
df.loc[~df['Province'].isin(df_provinces['Subdivision Name'])]

,Region,Province,City/Municipality,Foreign Travelers,Overseas Filipinos,Domestic Travelers,Total
278,Region IV-B,Occidental Mindoro,Abra de Ilog,0,0,0,0.0
279,Region IV-B,Occidental Mindoro,Calintaan,0,0,0,0.0
280,Region IV-B,Occidental Mindoro,Looc,0,0,0,0.0
281,Region IV-B,Occidental Mindoro,Lubang,26,0,7213,7239.0
282,Region IV-B,Occidental Mindoro,Magsaysay,0,0,186,186.0
283,Region IV-B,Occidental Mindoro,Mamburao,53,0,10619,10672.0
284,Region IV-B,Occidental Mindoro,Puluan,2,0,2313,2315.0
285,Region IV-B,Occidental Mindoro,Rizal,46,0,6569,6615.0
286,Region IV-B,Occidental Mindoro,Sablayan,694,0,17326,18020.0
287,Region IV-B,Occidental Mindoro,San Jose,775,0,29919,30694.0
288,Region IV-B,Occidental Mindoro,Santa Cruz,0,0,0,0.0
289,Region IV-B,Oriental Mindoro,Baco,0,0,170,170.0
290,Region IV-B,Oriental Mindoro,Bansud,9,0,1199,1208.0
291,Region IV-B,Oriental Mindoro,Bongabong,0,0,1340,1340.0
292,Region IV-B,Oriental Mindoro,Bulalacao,47,0,30293,30340.0
293,Region IV-B,Oriental Mindoro,Calapan City,572,0,55123,55695.0
294,Region IV-B,Oriental Mindoro,Gloria,28,0,16772,16800.0
295,Region IV-B,Oriental Mindoro,Mansalay,95,0,12408,12503.0
296,Region IV-B,Oriental Mindoro,Naujan,54,0,5121,5175.0
297,Region IV-B,Oriental Mindoro,Pinamalayan,163,0,20034,20197.0
298,Region IV-B,Oriental Mindoro,Pola,0,0,0,0.0
299,Region IV-B,Oriental Mindoro,Puerto Galera,7417,0,48777,56194.0
300,Region IV-B,Oriental Mindoro,Roxas,26,0,10668,10694.0
301,Region IV-B,Oriental Mindoro,San Teodoro,0,0,9019,9019.0
302,Region IV-B,Oriental Mindoro,Socorro,2912,0,4254,7166.0
303,Region IV-B,Oriental Mindoro,Victoria,0,0,7347,7347.0
729,Region IX,Zamboanga Del Norte,Dapitan City,22,0,19266,19288.0
730,Region IX,Zamboanga Del Norte,Dipolog City,92,0,92130,92222.0
731,Region IX,Zamboanga Del Norte,Others,632,0,187231,187863.0
736,Region IX,Zambonaga del Sur,Zamboanga City,1058,0,597368,598426.0
750,Region XI,Davao De Oro,NaN,775,0,291999,292774.0
751,Region XI,Davao Del Norte,NaN,652,0,479876,480528.0
753,Region XI,Davao Occcidental,NaN,0,0,0,0.0
756,Region XII,North Cotabato,Kidapawan City,0,0,143818,143818.0
757,Region XII,North Cotabato,Others (Cotabato Province),34,0,69915,69949.0

In [43]:
# changing the Mindoros names
df['Province'] = df['Province'].replace('Occidental Mindoro', 'Mindoro Occidental')
df['Province'] = df['Province'].replace('Oriental Mindoro', 'Mindoro Oriental')

In [44]:
#view provinces
df.loc[~df['Province'].isin(df_provinces['Subdivision Name'])]

,Region,Province,City/Municipality,Foreign Travelers,Overseas Filipinos,Domestic Travelers,Total
729,Region IX,Zamboanga Del Norte,Dapitan City,22,0,19266,19288.0
730,Region IX,Zamboanga Del Norte,Dipolog City,92,0,92130,92222.0
731,Region IX,Zamboanga Del Norte,Others,632,0,187231,187863.0
736,Region IX,Zambonaga del Sur,Zamboanga City,1058,0,597368,598426.0
750,Region XI,Davao De Oro,NaN,775,0,291999,292774.0
751,Region XI,Davao Del Norte,NaN,652,0,479876,480528.0
753,Region XI,Davao Occcidental,NaN,0,0,0,0.0
756,Region XII,North Cotabato,Kidapawan City,0,0,143818,143818.0
757,Region XII,North Cotabato,Others (Cotabato Province),34,0,69915,69949.0

In [62]:
#zamboangas
df['Province'] = df['Province'].replace('Zamboanga Del Norte', 'Zamboanga del Norte')
df['Province'] = df['Province'].replace('Zamboanga Del Sur', 'Zamboanga del Sur')
df['Province'] = df['Province'].replace('Zambonaga del Sur', 'Zamboanga del Sur')

In [65]:
#davaos
df['Province'] = df['Province'].replace('Davao De Oro', 'Davao de Oro')
df['Province'] = df['Province'].replace('Davao Del Norte', 'Davao del Norte')
df['Province'] = df['Province'].replace('Davao Occcidental', 'Davao Occidental')

In [66]:
#cotabatos
df['Province'] = df['Province'].replace('North Cotabato', 'Cotabato')

In [67]:
#view provinces
df.loc[~df['Province'].isin(df_provinces['Subdivision Name'])]

Empty DataFrame
Columns: [Region, Province, City/Municipality, Foreign Travelers, Overseas Filipinos, Domestic Travelers, Total]
Index: []

In [68]:
#export to excel
df.to_excel('Regional_tourism_data_processed.xlsx', index=False)